// services/templateRiskService.js
let templateRisks = [
  {
    riskId: "",
    department: "HR",
    date: "2025-09-16",
    riskType: "Strategic",
    assetType: "Private",
    asset: "Information",
    riskDescription: "Risk of loss of confidentiality of employee records due to unauthorized access  because of weak access controls",
    confidentiality: 3,
    integrity: 2,
    availability: 2,
    probability: 2,
    existingControls: "",
    additionalNotes: "",
    controlReference: "5.15",
    additionalControls: `Password-protected HRMS (but weak) 
Compensatory - 
1)Strong access control measures must be implemented.
2)Multi-factor authentication should be enforced for employee data, also.
3)User access rights must be reviewed monthly.`,
    numberOfDays: 17,
    deadlineDate: "2025-10-03",
    status: "Active",
    riskScore: 6,
    riskLevel: "Medium",
    likelihoodAfterTreatment: 1,
    impactAfterTreatment: 1,
    createdAt: "2025-09-16T07:52:48.209Z",
    updatedAt: "2025-09-19T05:38:13.797Z",
  },
  {
    riskId: "",
    department: "HR",
    date: "2025-09-22",
    riskType: "Tactical",
    assetType: "Private",
    asset: "Database",
    riskDescription: "Risk of stealing sensitive information due to a malicious insider because of weak background verification.",
    confidentiality: 2,
    integrity: 2,
    availability: 2,
    probability: 2,
    existingControls: "",
    additionalNotes: "",
    controlReference: "6.8",
    additionalControls: `Basic background checks
Compensatory - 
1)Employee background checks must be carried out thoroughly before hiring.
2)Confidentiality obligations must be clearly defined and enforced.
3)Privileged user activity must be monitored closely.`,
    numberOfDays: 47,
    deadlineDate: "2025-11-08",
    status: "Active",
    riskScore: 4,
    riskLevel: "Medium",
    likelihoodAfterTreatment: 1,
    impactAfterTreatment: 1,
    createdAt: "2025-09-22T10:07:13.277Z",
    updatedAt: "2025-09-22T10:07:55.704Z",
  },
  {
    riskId: "",
    department: "HR",
    date: "2025-09-16",
    riskType: "Strategic",
    assetType: "Private",
    asset: "Server",
    riskDescription: "Risk of loss of info",
    confidentiality: 2,
    integrity: 2,
    availability: 2,
    probability: 3,
    existingControls: "",
    additionalNotes: "",
    controlReference: "5.34,6.9",
    additionalControls: "DO something",
    numberOfDays: 17,
    deadlineDate: "2025-10-03",
    status: "Active",
    riskScore: 6,
    riskLevel: "Medium",
    likelihoodAfterTreatment: 1,
    impactAfterTreatment: 2,
    createdAt: "2025-09-16T07:52:48.209Z",
    updatedAt: "2025-09-19T05:38:13.797Z",
  },
  {
    riskId: "",
    department: "HR",
    date: "2025-09-16",
    riskType: "Strategic",
    assetType: "Private",
    asset: "Server",
    riskDescription: "Risk of unauthorized access after employee exit due to ex-employee misuse because of mishandling of offboarding.",
    confidentiality: 2,
    integrity: 2,
    availability: 2,
    probability: 3,
    existingControls: "",
    additionalNotes: "",
    controlReference: "5.34,6.9",
    additionalControls: "DO something",
    numberOfDays: 17,
    deadlineDate: "2025-10-03",
    status: "Active",
    riskScore: 6,
    riskLevel: "Medium",
    likelihoodAfterTreatment: 1,
    impactAfterTreatment: 2,
    createdAt: "2025-09-16T07:52:48.209Z",
    updatedAt: "2025-09-19T05:38:13.797Z",
  },
  {
    riskId: "",
    department: "HR",
    date: "2025-09-16",
    riskType: "Strategic",
    assetType: "Private",
    asset: "Server",
    riskDescription: "Risk of payroll data breach due to unauthorised access beacuase of weak access control",
    confidentiality: 2,
    integrity: 2,
    availability: 2,
    probability: 3,
    existingControls: "",
    additionalNotes: "",
    controlReference: "5.34,6.9",
    additionalControls: "DO something",
    numberOfDays: 17,
    deadlineDate: "2025-10-03",
    status: "Active",
    riskScore: 6,
    riskLevel: "Medium",
    likelihoodAfterTreatment: 1,
    impactAfterTreatment: 2,
    createdAt: "2025-09-16T07:52:48.209Z",
    updatedAt: "2025-09-19T05:38:13.797Z",
  },
  {
    riskId: "",
    department: "HR",
    date: "2025-09-16",
    riskType: "Strategic",
    assetType: "Private",
    asset: "Server",
    riskDescription: "Risk of fake transactions due to the manipulation of financial data.",
    confidentiality: 2,
    integrity: 2,
    availability: 2,
    probability: 3,
    existingControls: "",
    additionalNotes: "",
    controlReference: "5.34,6.9",
    additionalControls: "DO something",
    numberOfDays: 17,
    deadlineDate: "2025-10-03",
    status: "Active",
    riskScore: 6,
    riskLevel: "Medium",
    likelihoodAfterTreatment: 1,
    impactAfterTreatment: 2,
    createdAt: "2025-09-16T07:52:48.209Z",
    updatedAt: "2025-09-19T05:38:13.797Z",
  },
  {
    riskId: "",
    department: "HR",
    date: "2025-09-16",
    riskType: "Strategic",
    assetType: "Private",
    asset: "Server",
    riskDescription: "Risk of loss of info",
    confidentiality: 2,
    integrity: 2,
    availability: 2,
    probability: 3,
    existingControls: "",
    additionalNotes: "",
    controlReference: "5.34,6.9",
    additionalControls: "DO something",
    numberOfDays: 17,
    deadlineDate: "2025-10-03",
    status: "Active",
    riskScore: 6,
    riskLevel: "Medium",
    likelihoodAfterTreatment: 1,
    impactAfterTreatment: 2,
    createdAt: "2025-09-16T07:52:48.209Z",
    updatedAt: "2025-09-19T05:38:13.797Z",
  },
  {
    riskId: "",
    department: "HR",
    date: "2025-09-16",
    riskType: "Strategic",
    assetType: "Private",
    asset: "Server",
    riskDescription: "Risk of loss of info",
    confidentiality: 2,
    integrity: 2,
    availability: 2,
    probability: 3,
    existingControls: "",
    additionalNotes: "",
    controlReference: "5.34,6.9",
    additionalControls: "DO something",
    numberOfDays: 17,
    deadlineDate: "2025-10-03",
    status: "Active",
    riskScore: 6,
    riskLevel: "Medium",
    likelihoodAfterTreatment: 1,
    impactAfterTreatment: 2,
    createdAt: "2025-09-16T07:52:48.209Z",
    updatedAt: "2025-09-19T05:38:13.797Z",
  },
  {
    riskId: "",
    department: "HR",
    date: "2025-09-16",
    riskType: "Strategic",
    assetType: "Private",
    asset: "Server",
    riskDescription: "Risk of loss of info",
    confidentiality: 2,
    integrity: 2,
    availability: 2,
    probability: 3,
    existingControls: "",
    additionalNotes: "",
    controlReference: "5.34,6.9",
    additionalControls: "DO something",
    numberOfDays: 17,
    deadlineDate: "2025-10-03",
    status: "Active",
    riskScore: 6,
    riskLevel: "Medium",
    likelihoodAfterTreatment: 1,
    impactAfterTreatment: 2,
    createdAt: "2025-09-16T07:52:48.209Z",
    updatedAt: "2025-09-19T05:38:13.797Z",
  },
  {
    riskId: "",
    department: "HR",
    date: "2025-09-16",
    riskType: "Strategic",
    assetType: "Private",
    asset: "Server",
    riskDescription: "Risk of loss of info",
    confidentiality: 2,
    integrity: 2,
    availability: 2,
    probability: 3,
    existingControls: "",
    additionalNotes: "",
    controlReference: "5.34,6.9",
    additionalControls: "DO something",
    numberOfDays: 17,
    deadlineDate: "2025-10-03",
    status: "Active",
    riskScore: 6,
    riskLevel: "Medium",
    likelihoodAfterTreatment: 1,
    impactAfterTreatment: 2,
    createdAt: "2025-09-16T07:52:48.209Z",
    updatedAt: "2025-09-19T05:38:13.797Z",
  },
  {
    riskId: "",
    department: "HR",
    date: "2025-09-16",
    riskType: "Strategic",
    assetType: "Private",
    asset: "Server",
    riskDescription: "Risk of loss of info",
    confidentiality: 2,
    integrity: 2,
    availability: 2,
    probability: 3,
    existingControls: "",
    additionalNotes: "",
    controlReference: "5.34,6.9",
    additionalControls: "DO something",
    numberOfDays: 17,
    deadlineDate: "2025-10-03",
    status: "Active",
    riskScore: 6,
    riskLevel: "Medium",
    likelihoodAfterTreatment: 1,
    impactAfterTreatment: 2,
    createdAt: "2025-09-16T07:52:48.209Z",
    updatedAt: "2025-09-19T05:38:13.797Z",
  },
  {
    riskId: "",
    department: "HR",
    date: "2025-09-16",
    riskType: "Strategic",
    assetType: "Private",
    asset: "Server",
    riskDescription: "Risk of loss of info",
    confidentiality: 2,
    integrity: 2,
    availability: 2,
    probability: 3,
    existingControls: "",
    additionalNotes: "",
    controlReference: "5.34,6.9",
    additionalControls: "DO something",
    numberOfDays: 17,
    deadlineDate: "2025-10-03",
    status: "Active",
    riskScore: 6,
    riskLevel: "Medium",
    likelihoodAfterTreatment: 1,
    impactAfterTreatment: 2,
    createdAt: "2025-09-16T07:52:48.209Z",
    updatedAt: "2025-09-19T05:38:13.797Z",
  },
  {
    riskId: "",
    department: "HR",
    date: "2025-09-16",
    riskType: "Strategic",
    assetType: "Private",
    asset: "Server",
    riskDescription: "Risk of loss of info",
    confidentiality: 2,
    integrity: 2,
    availability: 2,
    probability: 3,
    existingControls: "",
    additionalNotes: "",
    controlReference: "5.34,6.9",
    additionalControls: "DO something",
    numberOfDays: 17,
    deadlineDate: "2025-10-03",
    status: "Active",
    riskScore: 6,
    riskLevel: "Medium",
    likelihoodAfterTreatment: 1,
    impactAfterTreatment: 2,
    createdAt: "2025-09-16T07:52:48.209Z",
    updatedAt: "2025-09-19T05:38:13.797Z",
  },
  {
    riskId: "",
    department: "HR",
    date: "2025-09-16",
    riskType: "Strategic",
    assetType: "Private",
    asset: "Server",
    riskDescription: "Risk of loss of info",
    confidentiality: 2,
    integrity: 2,
    availability: 2,
    probability: 3,
    existingControls: "",
    additionalNotes: "",
    controlReference: "5.34,6.9",
    additionalControls: "DO something",
    numberOfDays: 17,
    deadlineDate: "2025-10-03",
    status: "Active",
    riskScore: 6,
    riskLevel: "Medium",
    likelihoodAfterTreatment: 1,
    impactAfterTreatment: 2,
    createdAt: "2025-09-16T07:52:48.209Z",
    updatedAt: "2025-09-19T05:38:13.797Z",
  },
  {
    riskId: "",
    department: "HR",
    date: "2025-09-16",
    riskType: "Strategic",
    assetType: "Private",
    asset: "Server",
    riskDescription: "Risk of loss of info",
    confidentiality: 2,
    integrity: 2,
    availability: 2,
    probability: 3,
    existingControls: "",
    additionalNotes: "",
    controlReference: "5.34,6.9",
    additionalControls: "DO something",
    numberOfDays: 17,
    deadlineDate: "2025-10-03",
    status: "Active",
    riskScore: 6,
    riskLevel: "Medium",
    likelihoodAfterTreatment: 1,
    impactAfterTreatment: 2,
    createdAt: "2025-09-16T07:52:48.209Z",
    updatedAt: "2025-09-19T05:38:13.797Z",
  },
  {
    riskId: "",
    department: "HR",
    date: "2025-09-16",
    riskType: "Strategic",
    assetType: "Private",
    asset: "Server",
    riskDescription: "Risk of loss of info",
    confidentiality: 2,
    integrity: 2,
    availability: 2,
    probability: 3,
    existingControls: "",
    additionalNotes: "",
    controlReference: "5.34,6.9",
    additionalControls: "DO something",
    numberOfDays: 17,
    deadlineDate: "2025-10-03",
    status: "Active",
    riskScore: 6,
    riskLevel: "Medium",
    likelihoodAfterTreatment: 1,
    impactAfterTreatment: 2,
    createdAt: "2025-09-16T07:52:48.209Z",
    updatedAt: "2025-09-19T05:38:13.797Z",
  },
];

const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

export const getAllTemplateRisks = async () => {
  await delay(200);
  return [...templateRisks];
};

export const getTemplateRiskById = async (riskId) => {
  await delay(100);
  return templateRisks.find((r) => r.riskId === riskId);
};

export const saveTemplateRisk = async (risk) => {
  await delay(100);
  const index = templateRisks.findIndex((r) => r.riskId === risk.riskId);
  if (index > -1) {
    templateRisks[index] = { ...risk };
  } else {
    templateRisks.push({ ...risk });
  }
  return risk;
};

export const deleteTemplateRisk = async (riskId) => {
  await delay(100);
  templateRisks = templateRisks.filter((r) => r.riskId !== riskId);
  return true;
};

export default {
  getAllTemplateRisks,
  getTemplateRiskById,
  saveTemplateRisk,
  deleteTemplateRisk,
};
